# File to be duplicated on all worker nodes

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            equals:
              docker.container.labels.api_logging: "true"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"


- decode_json_fields:
    fields: ["message"]
    target: "logdata"
    overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"]

# logging.json: true
logging.metrics.enabled: false
# logging.level: debug
